ERP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda request: redirect('MM:login')),  # 默认重定向到登录页面
    path('mm/', include('MM.urls')),  # 确保替换为你的app名称
]

MM/urls.py
from django.urls import path, include
from django.contrib import admin
from .views import user, vendor, material, receipt, invoice, purchaserequisition, quotation, purchaseorder, document
from .views.ajax import material_api, data_api, stock_api, vendor_api, user_api, receipt_api, invoice_api
from django.shortcuts import redirect

app_name = 'MM'
urlpatterns = [
    # user
    path('login/', user.login, name='login'),
    path('register/', user.register, name='register'),
    path('home/', user.home, name='home'),
    path('logout/', user.logout, name='logout'),
    # vendor
    path('vendor/create/', vendor.create, name='create_vendor'),
    path('vendor/display/<int:pk>/', vendor.display, name='display_vendor'),
    path('vendor/search/', vendor.search, name='search_vendor'),
    path('vendor/history/', vendor.history, name='search_vendor_history'),
    # material
    path('material/search/', material.search_material, name='search_material'),
    path('material/item/create/', material.create_item, name='create_item'),
    path('material/item/stock/', material.search_item_stock, name='search_item_stock'),
    # receipt
    path('receipt/display/', receipt.display_receipt, name='display_receipt'),
    path('receipt/search/', receipt.search_receipt, name='search_receipt'),
    path('receipt/create/', receipt.load_order_item, name='load_order_item_receipt'),
    path('receipt/order/display/<int:pk>/', receipt.display_purchase_order, name='display_order_receipt'),
    path('receipt/orders/search/', receipt.search_orders, name='search_orders_receipt'),
    # invoice
    path('invoice/create/', invoice.load_order_item, name='load_order_item_invoice'),
    path('invoice/search/', invoice.search_invoice, name='search_invoice'),
    path('invoice/display/', invoice.display_invoice, name='display_invoice'),
    path('invoice/payment/', invoice.payment, name='pay_invoice'),
    path('invoice/order/display/<int:pk>/', invoice.display_purchase_order, name='display_order_invoice'),
    path('invoice/orders/search/', invoice.search_orders, name='search_orders_invoice'),
    # document flow
    path('document/search/', document.search_document_flow, name='search_document_flow'),
    path('document/display/<int:pk>/', document.display_document_flow, name='display_document_flow'),

    # ajax
    ## user
    path('api/user/loadAll/', user_api.load_user, name='ajax_load_user'),
    path('get_user_info/', user_api.get_user_info, name='get_user_info'),
    ## vendor
    path('api/vendor/update/', vendor_api.update_vendor, name='ajax_update_vendor'),
    path('api/vendor/search/', vendor_api.search_vendor, name='ajax_search_vendor'),
    path('api/vendor/create/', vendor_api.create_vendor, name='ajax_create_vendor'),
    path('api/vendor/score/', vendor_api.search_vendor_history, name='ajax_search_vendor_history'),
    path('api/vendor/search_info/', vendor_api.get_countries_and_companies, name='get_countries_and_companies'),
    ## material
    path('api/material/item/search/', material_api.search_item, name='ajax_search_item'),
    path('api/material/item/update/', material_api.update_item, name='ajax_update_item'),
    path('api/material/item/create/', material_api.create_item, name='ajax_create_item'),
    path('api/material/item/stockHistory/', material_api.update_item, name='ajax_update_item'),
    path('api/material/stock/search/', material_api.search_stock_history, name='ajax_search_stock_history'),
    path('api/material/stock/getByName/', stock_api.getByName, name='ajax_getStockByName'),
    ## receipt
    path('api/receipt/create/', receipt_api.create_receipt, name='ajax_create_receipt'),
    path('api/receipt/search/', receipt_api.search_receipt, name='ajax_search_receipt'),
    ## invoice
    path('api/invoice/search/', invoice_api.search_invoice, name='ajax_search_invoice'),
    path('api/invoice/create/', invoice_api.create_invoice, name='ajax_create_invoice'),
    path('api/invoice/searchUnpaid/', invoice_api.search_unpaied_invoice, name='ajax_search_unpaied_invoice'),
    path('api/invoice/pay/', invoice_api.pay, name='ajax_pay_invoice'),
    # pre-determined data
    path('api/data/country/', data_api.load_country, name='ajax_load_country'),
    path('api/data/company/', data_api.load_company, name='ajax_load_company'),
    path('api/data/currency/', data_api.load_currency, name='ajax_load_currency'),
    path('api/data/language/', data_api.load_language, name='ajax_load_language'),
    path('api/data/meaunit/', data_api.load_meaunit, name='ajax_load_meaunit'),
    path('api/data/pgrp/', data_api.load_pgrp, name='ajax_load_pgrp'),
    path('api/data/plant/', data_api.load_plant, name='ajax_load_plant'),
    path('api/data/porg/', data_api.load_porg, name='ajax_load_porg'),
    path('api/data/sorg/', data_api.load_sorg, name='ajax_load_sorg'),
    path('api/data/tptype/', data_api.load_tptype, name='ajax_load_tptype'),
    ##
    path('purchaserequisition/insert/', purchaserequisition.insert, name='insert_pur'),
    path('purchaserequisition/insertreque/', purchaserequisition.requeinsert, name='insert_pur'),
    path('purchaserequisition/delete/', purchaserequisition.deletereque, name='display_item'),
    path('purchaserequisition/getpq/', purchaserequisition.getpq, name='insert_pur'),
    path('purchaserequisition/getpqinfo/<int:pk>/', purchaserequisition.getpqinfo, name='insert_pur'),
    path('purchaserequisition/newinsertreque/', purchaserequisition.newrequeinsert, name='insert_pur'),

    path('quotation/getall', quotation.getall, name='search_pur'),
    path('quotation/searchqinggou', quotation.searchqinggou, name='search_pur'),
    path('quotation/searchquo', quotation.searchquo, name='search_pur'),
    path('quotation/vqcreate/<int:pk>/', purchaseorder.vqcreate, name='search_pur'),
    path('quotation/vqcreatejiekou/', purchaseorder.vqcreatejiekou, name='search_pur'),
    path('quotation/vreview/', purchaseorder.vreview, name='search_pur'),

    path('purchaseorder/pcs/', quotation.pcs, name='search_pur'),
    path('purchaseorder/info/<int:pk>/', purchaseorder.poinfo, name='search_pur'),
    path('purchaseorder/modifyinfo/<int:pk>/', purchaseorder.pomodifyinfo, name='search_pur'),
    path('purchaseorder/modifyinfo2/', purchaseorder.pomodifyinfo2, name='search_pur'),
    path('purchaseorder/modifyinfo3/', purchaseorder.pomodifyinfo3, name='search_pur'),
    path('purchaseorder/cresys/<int:pk>/', purchaserequisition.createsys, name='search_pur'),
    path('purchaseorder/cremanujiekou/', purchaserequisition.creamanujiekou, name='search_pur'),
    path('purchaseorder/quomodify/<int:pk>/', purchaserequisition.quomodify, name='search_pur'),
    path('purchaseorder/quomodifyjiekou/', purchaserequisition.quomodifyjiekou, name='search_pur'),

    path('quotation/makebyrq/<int:pk>/<int:itemId>', quotation.makebyrq, name='search_pur'),
    path('quotation/rfqinfo', quotation.rfqinfojiekou, name='search_pur'),
    path('purchaseorder/searchpo', purchaseorder.searchpo, name='search_pur'),
    path('purchaseorder/choose', purchaseorder.choose, name='search_pur'),
    path('quotation/searchqo', purchaseorder.searchqo, name='search_pur'),
    path('purchaserequisition/getmodifyinfo/<int:pk>/', purchaserequisition.getmodifyinfo, name='insert_pur'),
    path('purchaserequisition/getmodifyinfo2/', purchaserequisition.getmodifyinfo2, name='insert_pur'),
    path('quotation/rfqcreateinfo/<int:pk>/', quotation.rfqinfo, name='insert_pur'),
    path('quotation/rfqinfo/<int:pk>/', quotation.rfqinfo2, name='insert_pur'),
    path('purchaseorder/searchjiekou', purchaseorder.searchjiekou, name='search_pur'),
    path('purchaseorder/searchjiekouzhuanhua', purchaseorder.searchjiekouzhuanhua, name='search_pur'),
    path('purchaserequisition/pomanage', purchaserequisition.pomanage, name='search_pur'),
    path('purchaserequisition/prmanage', purchaserequisition.prmanage, name='search_pur'),
    path('purchaserequisition/quoma', purchaserequisition.quoma, name='search_pur'),
]

MM/views/auxiliary.py
import datetime
import pytz

def getRegex(string):
    if string == '' or string is None:
        return r'.*'
    else:
        return string

def getPk(string, type='*'):
    if string == '' or string is None:
        return r'.*'
    else:
        return str(int(string))

def getPkExact(string, type='*'):
    if string == '' or string is None:
        return ''
    else:
        return str(int(string))

def getDate(string):
    dateInfo = string.split('. ')
    string = datetime.date(
        year=int(dateInfo[2]), month=int(dateInfo[1]), day=int(dateInfo[0])
    )
    return string


def getDate2(string):
    dateInfo = string.split('. ')
    string = datetime.date(
        year=int(dateInfo[2]), month=int(dateInfo[1]), day=int(dateInfo[0])
    )
    return string

MM/views/document.py
import json
from django.shortcuts import get_object_or_404, render
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib import auth, messages
from django import forms
from django.db.models import QuerySet, Sum, F
from django.contrib.auth.decorators import login_required
from django.forms.models import model_to_dict
from django.utils import timezone
from datetime import datetime, timedelta
import datetime
from django.http import JsonResponse

from ..models import *
from .auxiliary import *


@login_required
def search_document_flow(request: HttpRequest):
    if request.method == 'POST':
        materialitem_id = request.POST.get('materialitemid')
        time_range = request.POST.get('time_range')

        orderitems = OrderItem.objects.all()

        if materialitem_id:
            orderitems = orderitems.filter(meterialItem__id__exact=materialitem_id)

        if time_range == '1':  # 近半年
            start_date = datetime.datetime.now() - datetime.timedelta(days=182)
        elif time_range == '2':  # 近三月
            start_date = datetime.datetime.now() - datetime.timedelta(days=91)
        else:
            start_date = None

        if start_date:
            orderitems = orderitems.filter(po__time__gte=start_date)

        data = {
            'orderitems': list(orderitems.values('po', 'po__euser__id', 'po__vendor__vname', 'id', 'itemId',
                                                 'meterialItem__material__mname', 'po__time')),
        }

        return JsonResponse(data)

    return render(
        request=request,
        template_name='../templates/document/search.html'
    )

@login_required
def display_document_flow(request: HttpRequest, pk):
    if request.method != 'POST':
        orderitem = get_object_or_404(OrderItem, pk=pk)
        po=orderitem.po
        materialitem = orderitem.meterialItem
        material=materialitem.material
        stock=materialitem.stock
        invoice=Invoice.objects.filter(orderItem=orderitem).first()
        goodreceipt=GoodReceipt.objects.filter(orderItem=orderitem).first()
        invoice_dict={}
        goodreceipt_dict={}
        if(invoice):
            invoice_dict = model_to_dict(invoice)
        if(goodreceipt):
            goodreceipt_dict = model_to_dict(goodreceipt)
        po_dict = model_to_dict(po)
        po_dict['time'] = po.time.strftime('%Y-%m-%d %H:%M:%S')  # Format datetime to string
        data = {
            'material': model_to_dict(material),
            'stock': model_to_dict(stock),
            'materialitem': model_to_dict(materialitem),
            'po': po_dict,
            'orderitem': model_to_dict(orderitem),
            'goodreceipt': goodreceipt_dict,
            'invoice': invoice_dict
        }

        return render(
            request=request,
            template_name='../templates/document/display.html',
            context=data
        )

MM/views/material.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib import auth, messages
from django import forms
from django.contrib.auth.decorators import login_required

from ..models import EUser, Material, MaterialItem, Stock
from .auxiliary import *

@login_required
def search_material(request: HttpRequest):
    if request.method == 'GET':
        return render(
            request=request,
            template_name='../templates/material/search.html'
        )
    else:
        return HttpResponse(status=405)

@login_required
def search_item_stock(request: HttpRequest):
    if request.method == 'GET':
        return render(
            request=request,
            template_name='../templates/material/stock.html'
        )
    else:
        return HttpResponse(status=405)

@login_required
def create_item(request: HttpRequest):
    if request.method == 'GET':
        return render(
            request=request,
            template_name='../templates/material/create.html'
        )
    else:
        return HttpResponse(status=405)

MM/views/user.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
import re
from django.shortcuts import redirect

from ..models import EUser

def login(request: HttpRequest) -> HttpResponse:
    if request.method == 'GET':
        return render(
            request=request,
            template_name='../templates/user/login.html',
        )
    elif request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        message = None
        if (password=='' or email==''):
            message = "部分字段为空"
        else:
            queryset = EUser.objects.filter(email__exact=email)
            if len(queryset) == 0:
                message = "用户名错误"
            else:
                euser = auth.authenticate(username=queryset.get().username, password=password)
                if euser is None:
                    message = "密码错误"
        if message is None:
            auth.login(request=request, user=euser)
            return HttpResponseRedirect(reverse('MM:home'))
        else:
            return render(
                request=request,
                template_name='../templates/user/login.html',
                context={'message': message}
            )


def register(request: HttpRequest) -> HttpResponse:
    if request.method == 'GET':
        return render(
            request=request,
            template_name='../templates/user/register.html',
        )
    elif request.method == 'POST':
        post = request.POST
        username = post.get('username')
        first_name = post.get('first_name')
        last_name = post.get('last_name')
        password = post.get('password')
        password1 = post.get('password2')
        email = post.get('email')
        sector = post.get('sector')
        phone = post.get('phone')
        question1 = post.get('question1')
        answer1 = post.get('answer1')
        question2 = post.get('question2')
        answer2 = post.get('answer2')

        message = None

        # 检查是否有空字段
        if (username == '' or password == '' or password1 == '' or email == '' or sector == '' or phone == '' or
                question1 == '' or question2 == '' or answer1 == '' or answer2 == ''):
            message = "部分字段为空"

        # 检查密码是否包含字母和数字
        elif not (re.search(r'[A-Za-z]', password) and re.search(r'[0-9]', password)):
            message = "密码必须同时包含字母和数字"

        # 检查电话是否为11位数字
        elif not re.match(r'^\d{11}$', phone):
            message = "电话必须为11位数字"

        # 检查邮箱格式是否正确
        elif not re.match(r'^[\w\.-]+@[\w\.-]+\.\w+$', email):
            message = "邮箱格式不正确"

        # 检查两次密码是否一致
        elif password != password1:
            message = "两次输入的密码不一致"

        # 检查邮箱是否已经注册
        else:
            queryset = EUser.objects.filter(email__exact=email)
            if len(queryset) > 0:
                message = "您的邮箱已被注册过"
            queryset = EUser.objects.filter(username__exact=username)
            if len(queryset) > 0:
                message = "您的用户名已被注册过"

        if message is None:
            euser = EUser(
                username=username,
                first_name=first_name,
                last_name=last_name,
                sector=sector,
                phone=phone,
                email=email,
                question1=question1, question2=question2,
                answer1=answer1, answer2=answer2,
            )
            euser.set_password(password)
            euser.save()
            messages.success(request=request, message="用户创建成功！")
            return HttpResponseRedirect(reverse('MM:login'))
        else:
            messages.error(request, message)
            return redirect('MM:register')


@login_required
def home(request):
    return render(
        request=request,
        template_name='../templates/user/index.html',
    )
    # return HttpResponse(request.user.username)

def logout(request):
    auth.logout(request=request)
    return HttpResponseRedirect(reverse('MM:login'))

MM/templates/quotation/RFQ.html
{% extends 'template.html' %} {% load static %} {% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'assets/css/RFQ_2.css' %}">
{% endblock %} {% block main_content %}
<section id="main-content">
  <section class="wrapper">
    <h3>查询报价申请</h3>
    <div class="row mt">
      <div class="col-lg-12">
        <div class="form-panel3">
          <form class="form-horizontal style-form" method="post">
            <div class="col-sm-9" id="rfq-search">
              <div id="rfq-search-row1">
                <div class="col-sm-1 col-sm-1 control-label" id="rfq-1">
                  报价申请单编码
                </div>
                <div class="col-sm-2" id="rfq-search1">
                  <input
                    type="text"
                    class="form-control"
                    name="id"
                    placeholder="请输入"
                  />
                </div>

                <div class="col-sm-1 col-sm-1 control-label" id="rfq-2">
                  供应商编码
                </div>
                <div class="col-sm-2" id="rfq-search3">
                  <input
                    type="text"
                    class="form-control"
                    name="vendor_id"
                    id="gyscode"
                    placeholder="请输入"
                  />
                  <button
                    type="button"
                    class="btn btn-link"
                    data-toggle="modal"
                    data-target="#myModalgys"
                  >
                    忘记编号？
                  </button>
                </div>
                <div
                  class="col-sm-1 col-sm-1 control-label"
                  id="rfq-3"
                  style="width: 160px"
                >
                  参考请购单编码
                </div>
                <div class="col-sm-2" id="rfq-search4">
                  <input
                    type="text"
                    class="form-control"
                    name="ri_id"
                    placeholder="请输入"
                    id="spcode"
                  />
                </div>
              </div>
              <br />
              <div id="rfq-search-row2">
                <div class="col-sm-1 col-sm-1 control-label" id="rfq-4">
                  集合码
                </div>
                <div class="col-sm-2" id="rfq-search2">
                  <input
                    type="text"
                    class="form-control"
                    name="collNo"
                    placeholder="请输入"
                  />
                </div>
                <div class="col-sm-1 col-sm-1 control-label" id="rfq-5">
                  创建者编码
                </div>
                <div class="col-sm-2" id="rfq-search5">
                  <input
                    type="text"
                    class="form-control"
                    placeholder="请输入"
                    name="euser_id"
                    onclick="openInsertModal()"
                    id="cjzcode"
                  />
                </div>
                <button
                  type="submit"
                  class="btn btn-success"
                  id="btn-rfq-search"
                >
                  搜索
                </button>
              </div>
              <br /><br /><br />

              <div class="col-sm-1"></div>
              {{ quotation }}

              <!-- </div> -->
            </div>
            <!-- <div class="col-lg-3">
                                
                            </div> -->
          </form>
        </div>
      </div>
    </div>

    <!--搜索供应商编码modal-->
    <div
      class="modal fade"
      id="myModalgys"
      tabindex="-1"
      role="dialog"
      aria-labelledby="myModalLabel1"
      aria-hidden="true"
    >
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button
              type="button"
              class="close"
              data-dismiss="modal"
              aria-hidden="true"
            >
              &times;
            </button>
            <h4 class="modal-title" id="myModalLabel">搜索供应商编号</h4>
          </div>
          <div class="modal-body">
            <!-- Hi there, I am a Modal Example for Dashgum Admin Panel. -->
            <!-- 搜索条件 -->
            <form id="material2" class="form-horizontal style-form">
              <div class="form-group">
                <!-- <label class="col-sm-1 col-sm-1 control-label"></label> -->
                <label class="col-sm-4 col-sm-4 control-label">
                  <div class="pull-right">供应商名称：</div>
                </label>
                <div class="col-sm-5">
                  <input
                    name="vname"
                    id="vname"
                    type="text"
                    class="form-control"
                  />
                </div>
              </div>
              <div class="form-group">
                <!-- <label class="col-sm-1 col-sm-1 control-label"></label> -->
                <label class="col-sm-4 col-sm-4 control-label">
                  <div class="pull-right">所在城市：</div>
                </label>
                <div class="col-sm-5">
                  <input
                    name="city"
                    id="city"
                    type="text"
                    class="form-control"
                  />
                </div>
              </div>
              <div class="form-group">
                <!-- <label class="col-sm-1 col-sm-1 control-label"></label> -->
                <label class="col-sm-4 col-sm-4 control-label">
                  <div class="pull-right">创建者编号：</div>
                </label>
                <div class="col-sm-5">
                  <input name="uid" id="uid" type="text" class="form-control" />
                </div>
              </div>
              <div class="form-group">
                <!-- <label class="col-sm-1 col-sm-1 control-label"></label> -->
                <label class="col-sm-4 col-sm-4 control-label">
                  <div class="pull-right">国家：</div>
                </label>
                <div class="col-sm-5">
                  <select class="form-control" name="country" id="country">
                    <option value="">请选择国家</option>
                  </select>
                </div>
              </div>
              <div class="form-group">
                <!-- <label class="col-sm-1 col-sm-1 control-label"></label> -->
                <label class="col-sm-4 col-sm-4 control-label">
                  <div class="pull-right">公司编码：</div>
                </label>
                <div class="col-sm-5">
                  <select class="form-control" name="company" id="company">
                    <option value="">请选择公司</option>
                  </select>
                </div>
                <div class="col-sm-2">
                  <input type="submit" class="btn btn-theme02" />
                </div>
              </div>
              <script>
                $(document).ready(function () {
                  $.ajax({
                    url: '{% url "MM:get_countries_and_companies" %}',
                    method: "GET",
                    success: function (data) {
                      var countrySelect = $("#country");
                      var companySelect = $("#company");

                      data.countries.forEach(function (country) {
                        countrySelect.append(
                          '<option value="' +
                            country +
                            '">' +
                            country +
                            "</option>"
                        );
                      });

                      data.companies.forEach(function (companyCode) {
                        companySelect.append(
                          '<option value="' +
                            companyCode +
                            '">' +
                            companyCode +
                            "</option>"
                        );
                      });
                    },
                    error: function (xhr, status, error) {
                      console.error("AJAX请求失败：", status, error);
                    },
                  });
                });
              </script>
            </form>
            <table class="table table-bordered table-striped table-condensed">
              *双击填入编号
              <thead>
                <!-- 搜索编号返回的属性 style="width: 100px;"-->
                <tr>
                  <th>供应商编号</th>
                  <th>供应商名称</th>
                  <th>所在城市</th>
                  <th>国家</th>
                  <th>公司编码</th>
                  <th>创建者编号</th>
                </tr>
              </thead>
              <tbody id="searchDiv"></tbody>
            </table>
            <script>
              $("#material2").on("submit", function (e) {
                e.preventDefault();
                $.ajax({
                  type: "POST",
                  url: "{% url 'MM:ajax_search_vendor' %}",
                  data: {
                    dataType: "json",
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                    vname: $("#vname").val(),
                    city: $("#city").val(),
                    country: $("#country").val(),
                    companyCode: $("#company").val(),
                    uid: $("#uid").val(),
                  },
                  success: function (data) {
                    $("#item_result").text(data);
                    var dataObj = eval("(" + data + ")");
                    var out = "";
                    var i;
                    for (i = 0; i < dataObj.length; i++) {
                      fields = dataObj[i].fields;
                      out +=
                        "<tr><td>" +
                        dataObj[i].pk +
                        "</td><td>" +
                        fields.vname +
                        "</td><td>" +
                        fields.city +
                        "</td><td>" +
                        fields.country +
                        "</td><td>" +
                        fields.companyCode +
                        "</td><td>" +
                        fields.euser +
                        "</td><tr>";
                    }
                    document.getElementById("searchDiv").innerHTML = out;
                  },
                  failure: function () {},
                });
              });
              //双击行 信息进入“搜索商品条件”三个框
              $("table").on("dblclick", "tr", function (e) {
                document.getElementById("gyscode").value = $(this)
                  .find("td")
                  .eq(0)
                  .text();
                $("#myModalgys").modal("hide");
              });
            </script>
          </div>

          <div class="modal-footer"></div>
        </div>
      </div>
    </div>

    <!--搜索供应商编码modal-->

    <div class="row mt">
      <div class="col-md-12">
        <div class="col-md-12">
          <div class="content-panel">
            <!-- <div class="form-panel2"> -->

            <table class="table table-striped table-advance table-hover">
              <h4><i class="fa fa-angle-right"></i> 报价申请列表</h4>
              <hr />
              <thead>
                <tr>
                  <th>报价申请单编码</th>
                  <th class="hidden-phone">创建者编码</th>
                  <th> 参考请购单编码</th>
                  <th class="hidden-phone">供应商编码</th>
                  <th>创建时间</th>
                  <th>操作</th>
                </tr>
              </thead>
              <tbody>
                {% for c in quoatations %}
                <tr>
                  <td>{{ c.id }}</td>
                  <td>{{ c.euser_id }}</td>
                  <td>{{ c.ri_id }}</td>
                  <td>{{ c.vendor_id }}</td>
                  <td>{{ c.time }}</td>
                  <td>
                    <!-- <button class="btn btn-success btn-xs"><i class="fa fa-check"></i></button> -->
                    <a href="/mm/quotation/rfqinfo/{{c.id}}/">
                      <button class="btn btn-success btn-xs">
                        <i class="fa fa-search-plus"></i>
                      </button>
                    </a>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <!-- /col-md-12 -->
  </section>
  <!--/wrapper -->
</section>
<!-- /MAIN CONTENT -->

<!--main content end-->
<!--footer start-->

<!--footer end-->

<!--script for this page-->

<!--script>
      //custom select box

      $(function(){
          $('select.styled').customSelect();
      });

      function openInsertModal() {

//弹出模态框

$("#myModalcjz").modal("show")

}



  </script-->
{% endblock %} {% block js %} {% endblock %}

MM/templates/quotation/makebyrq.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
            <div>
                <form class="form-login" action="" method="post">
                   {% csrf_token %}
		        <h2 class="form-login-heading">sign in now</h2>
		        <div class="login-wrap" id="login">
                    <input id="search-keyword-1" name="collNo" placeholder="集合码">
                    <input id="search-keyword-1" name="deadline" placeholder="截止日期">
                    <input id="search-keyword" name="quantity"  placeholder="数量">
                    <input id="search-keyword-1" name="deliveryDate" placeholder="交付日期">
                    <input id="search-keyword-1" name="rej" placeholder="拒绝情况">
                    <input id="search-keyword-1" name="vendorvid" placeholder="供应商ID">
                    <div style="text-align:center">
                         <button class="btn btn-theme"  type="submit" >Submit</button>
                    </div>
                    <hr>
		        </div>

		      </form>
                 {% if message %}
                    {{message}}
                     {% endif %}
            </div>
</body>
</html>