ERP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda request: redirect('MM:login')),  # 默认重定向到登录页面
    path('mm/', include('MM.urls')),  # 确保替换为你的app名称
]

MM/urls.py
from django.urls import path, include
from django.contrib import admin
from .views import user, vendor, material, receipt, invoice, purchaserequisition, quotation, purchaseorder, document
from .views.ajax import material_api, data_api, stock_api, vendor_api, user_api, receipt_api, invoice_api
from django.shortcuts import redirect

app_name = 'MM'
urlpatterns = [
    # user
    path('login/', user.login, name='login'),
    path('register/', user.register, name='register'),
    path('home/', user.home, name='home'),
    path('logout/', user.logout, name='logout'),
    # vendor
    path('vendor/create/', vendor.create, name='create_vendor'),
    path('vendor/display/<int:pk>/', vendor.display, name='display_vendor'),
    path('vendor/search/', vendor.search, name='search_vendor'),
    path('vendor/history/', vendor.history, name='search_vendor_history'),
    # material
    path('material/search/', material.search_material, name='search_material'),
    path('material/item/create/', material.create_item, name='create_item'),
    path('material/item/stock/', material.search_item_stock, name='search_item_stock'),
    # receipt
    path('receipt/display/', receipt.display_receipt, name='display_receipt'),
    path('receipt/search/', receipt.search_receipt, name='search_receipt'),
    path('receipt/create/', receipt.load_order_item, name='load_order_item_receipt'),
    path('receipt/order/display/<int:pk>/', receipt.display_purchase_order, name='display_order_receipt'),
    path('receipt/orders/search/', receipt.search_orders, name='search_orders_receipt'),
    # invoice
    path('invoice/create/', invoice.load_order_item, name='load_order_item_invoice'),
    path('invoice/search/', invoice.search_invoice, name='search_invoice'),
    path('invoice/display/', invoice.display_invoice, name='display_invoice'),
    path('invoice/payment/', invoice.payment, name='pay_invoice'),
    path('invoice/order/display/<int:pk>/', invoice.display_purchase_order, name='display_order_invoice'),
    path('invoice/orders/search/', invoice.search_orders, name='search_orders_invoice'),
    # document flow
    path('document/search/', document.search_document_flow, name='search_document_flow'),
    path('document/display/<int:pk>/', document.display_document_flow, name='display_document_flow'),

    # ajax
    ## user
    path('api/user/loadAll/', user_api.load_user, name='ajax_load_user'),
    path('get_user_info/', user_api.get_user_info, name='get_user_info'),
    ## vendor
    path('api/vendor/update/', vendor_api.update_vendor, name='ajax_update_vendor'),
    path('api/vendor/search/', vendor_api.search_vendor, name='ajax_search_vendor'),
    path('api/vendor/create/', vendor_api.create_vendor, name='ajax_create_vendor'),
    path('api/vendor/score/', vendor_api.search_vendor_history, name='ajax_search_vendor_history'),
    path('api/vendor/search_info/', vendor_api.get_countries_and_companies, name='get_countries_and_companies'),
    ## material
    path('api/material/item/search/', material_api.search_item, name='ajax_search_item'),
    path('api/material/item/update/', material_api.update_item, name='ajax_update_item'),
    path('api/material/item/create/', material_api.create_item, name='ajax_create_item'),
    path('api/material/item/stockHistory/', material_api.update_item, name='ajax_update_item'),
    path('api/material/stock/search/', material_api.search_stock_history, name='ajax_search_stock_history'),
    path('api/material/stock/getByName/', stock_api.getByName, name='ajax_getStockByName'),
    ## receipt
    path('api/receipt/create/', receipt_api.create_receipt, name='ajax_create_receipt'),
    path('api/receipt/search/', receipt_api.search_receipt, name='ajax_search_receipt'),
    ## invoice
    path('api/invoice/search/', invoice_api.search_invoice, name='ajax_search_invoice'),
    path('api/invoice/create/', invoice_api.create_invoice, name='ajax_create_invoice'),
    path('api/invoice/searchUnpaid/', invoice_api.search_unpaied_invoice, name='ajax_search_unpaied_invoice'),
    path('api/invoice/pay/', invoice_api.pay, name='ajax_pay_invoice'),
    # pre-determined data
    path('api/data/country/', data_api.load_country, name='ajax_load_country'),
    path('api/data/company/', data_api.load_company, name='ajax_load_company'),
    path('api/data/currency/', data_api.load_currency, name='ajax_load_currency'),
    path('api/data/language/', data_api.load_language, name='ajax_load_language'),
    path('api/data/meaunit/', data_api.load_meaunit, name='ajax_load_meaunit'),
    path('api/data/pgrp/', data_api.load_pgrp, name='ajax_load_pgrp'),
    path('api/data/plant/', data_api.load_plant, name='ajax_load_plant'),
    path('api/data/porg/', data_api.load_porg, name='ajax_load_porg'),
    path('api/data/sorg/', data_api.load_sorg, name='ajax_load_sorg'),
    path('api/data/tptype/', data_api.load_tptype, name='ajax_load_tptype'),
    ##
    path('purchaserequisition/insert/', purchaserequisition.insert, name='insert_pur'),
    path('purchaserequisition/insertreque/', purchaserequisition.requeinsert, name='insert_pur'),
    path('purchaserequisition/delete/', purchaserequisition.deletereque, name='display_item'),
    path('purchaserequisition/getpq/', purchaserequisition.getpq, name='insert_pur'),
    path('purchaserequisition/getpqinfo/<int:pk>/', purchaserequisition.getpqinfo, name='insert_pur'),
    path('purchaserequisition/newinsertreque/', purchaserequisition.newrequeinsert, name='insert_pur'),

    path('quotation/getall', quotation.getall, name='search_pur'),
    path('quotation/searchqinggou', quotation.searchqinggou, name='search_pur'),
    path('quotation/searchquo', quotation.searchquo, name='search_pur'),
    path('quotation/vqcreate/<int:pk>/', purchaseorder.vqcreate, name='search_pur'),
    path('quotation/vqcreatejiekou/', purchaseorder.vqcreatejiekou, name='search_pur'),
    path('quotation/vreview/', purchaseorder.vreview, name='search_pur'),

    path('purchaseorder/pcs/', quotation.pcs, name='search_pur'),
    path('purchaseorder/info/<int:pk>/', purchaseorder.poinfo, name='search_pur'),
    path('purchaseorder/modifyinfo/<int:pk>/', purchaseorder.pomodifyinfo, name='search_pur'),
    path('purchaseorder/modifyinfo2/', purchaseorder.pomodifyinfo2, name='search_pur'),
    path('purchaseorder/modifyinfo3/', purchaseorder.pomodifyinfo3, name='search_pur'),
    path('purchaseorder/cresys/<int:pk>/', purchaserequisition.createsys, name='search_pur'),
    path('purchaseorder/cremanujiekou/', purchaserequisition.creamanujiekou, name='search_pur'),
    path('purchaseorder/quomodify/<int:pk>/', purchaserequisition.quomodify, name='search_pur'),
    path('purchaseorder/quomodifyjiekou/', purchaserequisition.quomodifyjiekou, name='search_pur'),

    path('quotation/makebyrq/<int:pk>/<int:itemId>', quotation.makebyrq, name='search_pur'),
    path('quotation/rfqinfo', quotation.rfqinfojiekou, name='search_pur'),
    path('purchaseorder/searchpo', purchaseorder.searchpo, name='search_pur'),
    path('purchaseorder/choose', purchaseorder.choose, name='search_pur'),
    path('quotation/searchqo', purchaseorder.searchqo, name='search_pur'),
    path('purchaserequisition/getmodifyinfo/<int:pk>/', purchaserequisition.getmodifyinfo, name='insert_pur'),
    path('purchaserequisition/getmodifyinfo2/', purchaserequisition.getmodifyinfo2, name='insert_pur'),
    path('quotation/rfqcreateinfo/<int:pk>/', quotation.rfqinfo, name='insert_pur'),
    path('quotation/rfqinfo/<int:pk>/', quotation.rfqinfo2, name='insert_pur'),
    path('purchaseorder/searchjiekou', purchaseorder.searchjiekou, name='search_pur'),
    path('purchaseorder/searchjiekouzhuanhua', purchaseorder.searchjiekouzhuanhua, name='search_pur'),
    path('purchaserequisition/pomanage', purchaserequisition.pomanage, name='search_pur'),
    path('purchaserequisition/prmanage', purchaserequisition.prmanage, name='search_pur'),
    path('purchaserequisition/quoma', purchaserequisition.quoma, name='search_pur'),
]

MM/views/auxiliary.py
import datetime
import pytz

def getRegex(string):
    if string == '' or string is None:
        return r'.*'
    else:
        return string

def getPk(string, type='*'):
    if string == '' or string is None:
        return r'.*'
    else:
        return str(int(string))

def getPkExact(string, type='*'):
    if string == '' or string is None:
        return ''
    else:
        return str(int(string))

def getDate(string):
    dateInfo = string.split('. ')
    string = datetime.date(
        year=int(dateInfo[2]), month=int(dateInfo[1]), day=int(dateInfo[0])
    )
    return string


def getDate2(string):
    dateInfo = string.split('. ')
    string = datetime.date(
        year=int(dateInfo[2]), month=int(dateInfo[1]), day=int(dateInfo[0])
    )
    return string

MM/views/document.py
import json
from django.shortcuts import get_object_or_404, render
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib import auth, messages
from django import forms
from django.db.models import QuerySet, Sum, F
from django.contrib.auth.decorators import login_required
from django.forms.models import model_to_dict
from django.utils import timezone
from datetime import datetime, timedelta
import datetime
from django.http import JsonResponse

from ..models import *
from .auxiliary import *


@login_required
def search_document_flow(request: HttpRequest):
    if request.method == 'POST':
        materialitem_id = request.POST.get('materialitemid')
        time_range = request.POST.get('time_range')

        orderitems = OrderItem.objects.all()

        if materialitem_id:
            orderitems = orderitems.filter(meterialItem__id__exact=materialitem_id)

        if time_range == '1':  # 近半年
            start_date = datetime.datetime.now() - datetime.timedelta(days=182)
        elif time_range == '2':  # 近三月
            start_date = datetime.datetime.now() - datetime.timedelta(days=91)
        else:
            start_date = None

        if start_date:
            orderitems = orderitems.filter(po__time__gte=start_date)

        data = {
            'orderitems': list(orderitems.values('po', 'po__euser__id', 'po__vendor__vname', 'id', 'itemId',
                                                 'meterialItem__material__mname', 'po__time')),
        }

        return JsonResponse(data)

    return render(
        request=request,
        template_name='../templates/document/search.html'
    )

@login_required
def display_document_flow(request: HttpRequest, pk):
    if request.method != 'POST':
        orderitem = get_object_or_404(OrderItem, pk=pk)
        po=orderitem.po
        materialitem = orderitem.meterialItem
        material=materialitem.material
        stock=materialitem.stock
        invoice=Invoice.objects.filter(orderItem=orderitem).first()
        goodreceipt=GoodReceipt.objects.filter(orderItem=orderitem).first()
        invoice_dict={}
        goodreceipt_dict={}
        if(invoice):
            invoice_dict = model_to_dict(invoice)
        if(goodreceipt):
            goodreceipt_dict = model_to_dict(goodreceipt)
        po_dict = model_to_dict(po)
        po_dict['time'] = po.time.strftime('%Y-%m-%d %H:%M:%S')  # Format datetime to string
        data = {
            'material': model_to_dict(material),
            'stock': model_to_dict(stock),
            'materialitem': model_to_dict(materialitem),
            'po': po_dict,
            'orderitem': model_to_dict(orderitem),
            'goodreceipt': goodreceipt_dict,
            'invoice': invoice_dict
        }

        return render(
            request=request,
            template_name='../templates/document/display.html',
            context=data
        )

MM/views/material.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib import auth, messages
from django import forms
from django.contrib.auth.decorators import login_required

from ..models import EUser, Material, MaterialItem, Stock
from .auxiliary import *

@login_required
def search_material(request: HttpRequest):
    if request.method == 'GET':
        return render(
            request=request,
            template_name='../templates/material/search.html'
        )
    else:
        return HttpResponse(status=405)

@login_required
def search_item_stock(request: HttpRequest):
    if request.method == 'GET':
        return render(
            request=request,
            template_name='../templates/material/stock.html'
        )
    else:
        return HttpResponse(status=405)

@login_required
def create_item(request: HttpRequest):
    if request.method == 'GET':
        return render(
            request=request,
            template_name='../templates/material/create.html'
        )
    else:
        return HttpResponse(status=405)

MM/views/user.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
import re
from django.shortcuts import redirect

from ..models import EUser

def login(request: HttpRequest) -> HttpResponse:
    if request.method == 'GET':
        return render(
            request=request,
            template_name='../templates/user/login.html',
        )
    elif request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        message = None
        if (password=='' or email==''):
            message = "部分字段为空"
        else:
            queryset = EUser.objects.filter(email__exact=email)
            if len(queryset) == 0:
                message = "用户名错误"
            else:
                euser = auth.authenticate(username=queryset.get().username, password=password)
                if euser is None:
                    message = "密码错误"
        if message is None:
            auth.login(request=request, user=euser)
            return HttpResponseRedirect(reverse('MM:home'))
        else:
            return render(
                request=request,
                template_name='../templates/user/login.html',
                context={'message': message}
            )


def register(request: HttpRequest) -> HttpResponse:
    if request.method == 'GET':
        return render(
            request=request,
            template_name='../templates/user/register.html',
        )
    elif request.method == 'POST':
        post = request.POST
        username = post.get('username')
        first_name = post.get('first_name')
        last_name = post.get('last_name')
        password = post.get('password')
        password1 = post.get('password2')
        email = post.get('email')
        sector = post.get('sector')
        phone = post.get('phone')
        question1 = post.get('question1')
        answer1 = post.get('answer1')
        question2 = post.get('question2')
        answer2 = post.get('answer2')

        message = None

        # 检查是否有空字段
        if (username == '' or password == '' or password1 == '' or email == '' or sector == '' or phone == '' or
                question1 == '' or question2 == '' or answer1 == '' or answer2 == ''):
            message = "部分字段为空"

        # 检查密码是否包含字母和数字
        elif not (re.search(r'[A-Za-z]', password) and re.search(r'[0-9]', password)):
            message = "密码必须同时包含字母和数字"

        # 检查电话是否为11位数字
        elif not re.match(r'^\d{11}$', phone):
            message = "电话必须为11位数字"

        # 检查邮箱格式是否正确
        elif not re.match(r'^[\w\.-]+@[\w\.-]+\.\w+$', email):
            message = "邮箱格式不正确"

        # 检查两次密码是否一致
        elif password != password1:
            message = "两次输入的密码不一致"

        # 检查邮箱是否已经注册
        else:
            queryset = EUser.objects.filter(email__exact=email)
            if len(queryset) > 0:
                message = "您的邮箱已被注册过"
            queryset = EUser.objects.filter(username__exact=username)
            if len(queryset) > 0:
                message = "您的用户名已被注册过"

        if message is None:
            euser = EUser(
                username=username,
                first_name=first_name,
                last_name=last_name,
                sector=sector,
                phone=phone,
                email=email,
                question1=question1, question2=question2,
                answer1=answer1, answer2=answer2,
            )
            euser.set_password(password)
            euser.save()
            messages.success(request=request, message="用户创建成功！")
            return HttpResponseRedirect(reverse('MM:login'))
        else:
            messages.error(request, message)
            return redirect('MM:register')


@login_required
def home(request):
    return render(
        request=request,
        template_name='../templates/user/index.html',
    )
    # return HttpResponse(request.user.username)

def logout(request):
    auth.logout(request=request)
    return HttpResponseRedirect(reverse('MM:login'))

MM/templates/receipt/display.html
{% extends 'template.html' %}

{% load static %}
{% block extra_css %}

{% endblock %}


{% block main_content %}
    <section id="main-content">
        <section class="wrapper">
            <div class="row " style="margin: 30px 0 0 15px">
                <div class="col-sm-10">
                    <h3><i class="fa fa-angle-right"></i> 查看商品收据</h3>
                </div>
                <div class="col-sm-2" style="margin: 15px 0 0 0">
                    <button type="button" class="btn btn-theme03"
                            onclick="toPrint()"><i class="fa fa-print" aria-hidden="true"></i>
                        打印
                    </button>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="col-lg-12">
                        <br><br>
                        <div id='form'>
                            <div class="content-panel" id="print">
                                <div class="row">
                                <h4 style="text-align:center">商品收据</h4></div>
                                <div class="row" style="margin: 0 80px 0 80px">
                                <section id="unseen">

                                    <table class="table">
                                        <thead>
                                        <tr>
                                            <th>基本信息</th>

                                        </tr>
                                        </thead>

                                        <tbody>
                                        <tr>
                                            <td>
                                                <label>商品收据编码：</label>
                                                <label>{{ context.gr.id }}</label>
                                            </td>
                                            <td>
                                                <label>创建者编码：</label>
                                                <label>{{ context.gr.euser }}</label>
                                            </td>

                                        </tr>
                                        <tr>
                                            <td>
                                                <label>预期送达时间：</label>
                                                <label>{{ context.deliveryDate }}</label>
                                            </td>

                                            <td>
                                                <label>收货时间：</label>
                                                <label>{{ context.gr.time }}</label>
                                            </td>
                                            <td>
                                                <label>过账时间：</label>
                                                <label>{{ context.gr.postTime }}</label>
                                            </td>
                                        </tr>

                                        </tbody>

                                    </table>

                                    <table class="table">
                                        <thead>
                                        <tr>
                                            <th>商品详情</th>

                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td>
                                                <label>商品名称：</label>
                                                <label>{{ context.material.mname }}</label>
                                            </td>

                                            <td>
                                                <label>完整名称：</label>
                                                <label>{{ context.material.shortText }}</label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <label>应收数量：</label>
                                                <label>{{ context.quantity }}</label>
                                            </td>

                                            <td>
                                                <label>实收数量：</label>
                                                <label>{{ context.gr.actualQnty }}</label>
                                            </td>
                                        </tr>
                                        <thead>
                                        <tr>
                                            <th>库存信息</th>

                                        </tr>
                                        </thead>
                                        <tr>
                                            <td>
                                                <label>工厂：</label>
                                                <label>{{ context.stock.name }}</label>
                                            </td>

                                            <td>
                                                <label>存储位置：</label>
                                                <label>{{ context.materialItem.sloc }}</label>
                                            </td>
                                            <td>
                                                <label>库存类型：</label>
                                                <label>{{ context.gr.sType }}</label>
                                            </td>
                                        </tr>
                                        </tbody>
                                    </table>

                                </section></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </section>
    </section>
{% endblock %}

{% block js %}

    <script type="text/javascript">
        function toPrint() {
            $("#print").jqprint();
        }
    </script>
{% endblock %}

MM/templates/receipt/search.html
{% extends 'template.html' %}
{% load static %}
{% block extra_css %}
    <style>
    th{
        text-align: center;
    }
    td{
        text-align: center;
    }
    </style>
{% endblock %}

{% block main_content %}
    <section id="main-content">
        <section class="wrapper">
            <h3><i class="fa fa-angle-right"></i> 查看商品收据</h3>

            <div class="row mt">
                <div class="col-lg-12">
                    <div class="form-panel3">
                        <form id='material1' class="form-horizontal style-form" method="get">
                            <div class="col-sm-3">
                                <input class="form-control" type="text" placeholder="请输入收据编号" id="sjcode">
                            </div>
                            <div class="col-sm-3">
                                <input class="form-control" type="text" placeholder="请输入创建者编码"
                                       onclick="openInsertModal()" id="cjzcode">
                            </div>
                            <div class="col-sm-3">
                                <input class="form-control" type="text" id="my-input" placeholder="请输入创建日期">
                            </div>

                            <button type="submit" formmethod="post" class="btn btn-success "><i
                                    class="fa fa-search"></i>
                            </button>
                        </form>
                        <div id='details'>
                            <div class="row mt">
                                <div class="col-md-12">
                                    <div class="col-md-12">

                                        <div class="content-panel">
                                            <div style="margin: 15px">
                                            <table class="table table-striped table-advance table-hover">
                                                <h4><i class="fa fa-angle-right"></i> 商品收据列表</h4>
                                                <hr>
                                                <thead>
                                                <tr>
                                                    <th>收据编码</th>
                                                    <th>采购订单编码</th>
                                                    <th>条目编码</th>
                                                    <th>商品名称</th>
                                                    <th>数量</th>
                                                    <th>实收数量</th>
                                                    <th>创建时间</th>
                                                    <th>查看详情</th>
                                                </tr>
                                                </thead>
                                                <tbody id="searchDiv"></tbody>
                                            </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </section>
    </section>
{% endblock %}


{% block js %}
    <script>
        //收据搜索 不限制三项内容是否填写默认返回全部
        $('#material1').on('submit', function (e) {
            e.preventDefault();
            $.ajax(
                {
                    type: "POST",
                    url: "{% url 'MM:ajax_search_receipt' %}",
                    data: {
                        dataType: "json",
                        csrfmiddlewaretoken: '{{ csrf_token }}',
                        //输入三个搜索框的值
                        uid: $("#cjzcode").val(),
                        pk: $("#sjcode").val(),
                        date: $("#my-input").val(),
                    },
                    success: function (data) {
                        //$('#item_result').text(data);
                        var dataObj = eval("(" + data + ")");
                        //显示消息通知
                        if(dataObj.status==1)
                            showMessage({ text: dataObj.message, type: 'success' });
                        else
                            showMessage({ text: dataObj.message, type: 'error' });

                        var out = '';
                        for (i = 0; i < dataObj.gr.length; i++) {
                            content2 = dataObj.gr[i].fields
                            //": 10, "sType": "1", "time": "2022-08-18T10:05:04.605Z", "postTime": "2022-08-18T10:03:52Z", "orderItem": 1, "euser": 1}, "user": {"id": 2,

                            out += '<tr><td id="grpk' + i + '">' + dataObj.gr[i].pk + '</td><td id="itempk' + i + '">' + dataObj.gr[i].orderItem.po + '</td><td id="orpk' + i + '">' + dataObj.gr[i].orderItem.itemId + '</td><td>' + dataObj.gr[i].material + '</td><td>' + dataObj.gr[i].orderItem.quantity + '</td><td>' + content2.actualQnty + '</td><td>' + content2.time.substr(0, 10) + '</td><td><button class="btn btn-success btn-xs" onclick="submitpk(this.id)" id="bid' + i + '"><i class="fa fa-search-plus"></i></button></td></tr>';
                        }
                        $('#item_result1').text(out);
                        document.getElementById("searchDiv").innerHTML = out;
                    },
                    failure: function () {

                    }
                })
        });

        //点击按钮，收据编码给后端
        function submitpk(clicked_id) {

            var suffix = clicked_id.substring(3);  // 或者使用 clicked_id.slice(3)
            var grpk = "#grpk" + suffix;
            var itempk = "#itempk" + suffix;
            var orpk = "#orpk" + suffix;
            console.log($(orpk).html());
            //待补充，两个参数    dataObj.gr[i].orderItem.itemId dataObj.gr[i].po.id
            var target = "{% url 'MM:display_receipt' %}" + '?' + 'grID=' + $(grpk).html() + '&' + 'itemID=' + $(orpk).html() + '&' + 'orderID=' + $(itempk).html();
            window.location.href = target;

        }
    </script>

    <!-- 日期选择器 -->
    <script>
        (function () {
            const input = document.getElementById('my-input');
            const datepicker = new TheDatepicker.Datepicker(input);
            datepicker.render();
        })();
    </script>
{% endblock %}