ERP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda request: redirect('MM:login')),  # 默认重定向到登录页面
    path('mm/', include('MM.urls')),  # 确保替换为你的app名称
]

MM/urls.py
from django.urls import path, include
from django.contrib import admin
from .views import user, vendor, material, receipt, invoice, purchaserequisition, quotation, purchaseorder, document
from .views.ajax import material_api, data_api, stock_api, vendor_api, user_api, receipt_api, invoice_api
from django.shortcuts import redirect

app_name = 'MM'
urlpatterns = [
    # user
    path('login/', user.login, name='login'),
    path('register/', user.register, name='register'),
    path('home/', user.home, name='home'),
    path('logout/', user.logout, name='logout'),
    # vendor
    path('vendor/create/', vendor.create, name='create_vendor'),
    path('vendor/display/<int:pk>/', vendor.display, name='display_vendor'),
    path('vendor/search/', vendor.search, name='search_vendor'),
    path('vendor/history/', vendor.history, name='search_vendor_history'),
    # material
    path('material/search/', material.search_material, name='search_material'),
    path('material/item/create/', material.create_item, name='create_item'),
    path('material/item/stock/', material.search_item_stock, name='search_item_stock'),
    # receipt
    path('receipt/display/', receipt.display_receipt, name='display_receipt'),
    path('receipt/search/', receipt.search_receipt, name='search_receipt'),
    path('receipt/create/', receipt.load_order_item, name='load_order_item_receipt'),
    path('receipt/order/display/<int:pk>/', receipt.display_purchase_order, name='display_order_receipt'),
    path('receipt/orders/search/', receipt.search_orders, name='search_orders_receipt'),
    # invoice
    path('invoice/create/', invoice.load_order_item, name='load_order_item_invoice'),
    path('invoice/search/', invoice.search_invoice, name='search_invoice'),
    path('invoice/display/', invoice.display_invoice, name='display_invoice'),
    path('invoice/payment/', invoice.payment, name='pay_invoice'),
    path('invoice/order/display/<int:pk>/', invoice.display_purchase_order, name='display_order_invoice'),
    path('invoice/orders/search/', invoice.search_orders, name='search_orders_invoice'),
    # document flow
    path('document/search/', document.search_document_flow, name='search_document_flow'),
    path('document/display/<int:pk>/', document.display_document_flow, name='display_document_flow'),

    # ajax
    ## user
    path('api/user/loadAll/', user_api.load_user, name='ajax_load_user'),
    path('get_user_info/', user_api.get_user_info, name='get_user_info'),
    ## vendor
    path('api/vendor/update/', vendor_api.update_vendor, name='ajax_update_vendor'),
    path('api/vendor/search/', vendor_api.search_vendor, name='ajax_search_vendor'),
    path('api/vendor/create/', vendor_api.create_vendor, name='ajax_create_vendor'),
    path('api/vendor/score/', vendor_api.search_vendor_history, name='ajax_search_vendor_history'),
    path('api/vendor/search_info/', vendor_api.get_countries_and_companies, name='get_countries_and_companies'),
    ## material
    path('api/material/item/search/', material_api.search_item, name='ajax_search_item'),
    path('api/material/item/update/', material_api.update_item, name='ajax_update_item'),
    path('api/material/item/create/', material_api.create_item, name='ajax_create_item'),
    path('api/material/item/stockHistory/', material_api.update_item, name='ajax_update_item'),
    path('api/material/stock/search/', material_api.search_stock_history, name='ajax_search_stock_history'),
    path('api/material/stock/getByName/', stock_api.getByName, name='ajax_getStockByName'),
    ## receipt
    path('api/receipt/create/', receipt_api.create_receipt, name='ajax_create_receipt'),
    path('api/receipt/search/', receipt_api.search_receipt, name='ajax_search_receipt'),
    ## invoice
    path('api/invoice/search/', invoice_api.search_invoice, name='ajax_search_invoice'),
    path('api/invoice/create/', invoice_api.create_invoice, name='ajax_create_invoice'),
    path('api/invoice/searchUnpaid/', invoice_api.search_unpaied_invoice, name='ajax_search_unpaied_invoice'),
    path('api/invoice/pay/', invoice_api.pay, name='ajax_pay_invoice'),
    # pre-determined data
    path('api/data/country/', data_api.load_country, name='ajax_load_country'),
    path('api/data/company/', data_api.load_company, name='ajax_load_company'),
    path('api/data/currency/', data_api.load_currency, name='ajax_load_currency'),
    path('api/data/language/', data_api.load_language, name='ajax_load_language'),
    path('api/data/meaunit/', data_api.load_meaunit, name='ajax_load_meaunit'),
    path('api/data/pgrp/', data_api.load_pgrp, name='ajax_load_pgrp'),
    path('api/data/plant/', data_api.load_plant, name='ajax_load_plant'),
    path('api/data/porg/', data_api.load_porg, name='ajax_load_porg'),
    path('api/data/sorg/', data_api.load_sorg, name='ajax_load_sorg'),
    path('api/data/tptype/', data_api.load_tptype, name='ajax_load_tptype'),
    ##
    path('purchaserequisition/insert/', purchaserequisition.insert, name='insert_pur'),
    path('purchaserequisition/insertreque/', purchaserequisition.requeinsert, name='insert_pur'),
    path('purchaserequisition/delete/', purchaserequisition.deletereque, name='display_item'),
    path('purchaserequisition/getpq/', purchaserequisition.getpq, name='insert_pur'),
    path('purchaserequisition/getpqinfo/<int:pk>/', purchaserequisition.getpqinfo, name='insert_pur'),
    path('purchaserequisition/newinsertreque/', purchaserequisition.newrequeinsert, name='insert_pur'),

    path('quotation/getall', quotation.getall, name='search_pur'),
    path('quotation/searchqinggou', quotation.searchqinggou, name='search_pur'),
    path('quotation/searchquo', quotation.searchquo, name='search_pur'),
    path('quotation/vqcreate/<int:pk>/', purchaseorder.vqcreate, name='search_pur'),
    path('quotation/vqcreatejiekou/', purchaseorder.vqcreatejiekou, name='search_pur'),
    path('quotation/vreview/', purchaseorder.vreview, name='search_pur'),

    path('purchaseorder/pcs/', quotation.pcs, name='search_pur'),
    path('purchaseorder/info/<int:pk>/', purchaseorder.poinfo, name='search_pur'),
    path('purchaseorder/modifyinfo/<int:pk>/', purchaseorder.pomodifyinfo, name='search_pur'),
    path('purchaseorder/modifyinfo2/', purchaseorder.pomodifyinfo2, name='search_pur'),
    path('purchaseorder/modifyinfo3/', purchaseorder.pomodifyinfo3, name='search_pur'),
    path('purchaseorder/cresys/<int:pk>/', purchaserequisition.createsys, name='search_pur'),
    path('purchaseorder/cremanujiekou/', purchaserequisition.creamanujiekou, name='search_pur'),
    path('purchaseorder/quomodify/<int:pk>/', purchaserequisition.quomodify, name='search_pur'),
    path('purchaseorder/quomodifyjiekou/', purchaserequisition.quomodifyjiekou, name='search_pur'),

    path('quotation/makebyrq/<int:pk>/<int:itemId>', quotation.makebyrq, name='search_pur'),
    path('quotation/rfqinfo', quotation.rfqinfojiekou, name='search_pur'),
    path('purchaseorder/searchpo', purchaseorder.searchpo, name='search_pur'),
    path('purchaseorder/choose', purchaseorder.choose, name='search_pur'),
    path('quotation/searchqo', purchaseorder.searchqo, name='search_pur'),
    path('purchaserequisition/getmodifyinfo/<int:pk>/', purchaserequisition.getmodifyinfo, name='insert_pur'),
    path('purchaserequisition/getmodifyinfo2/', purchaserequisition.getmodifyinfo2, name='insert_pur'),
    path('quotation/rfqcreateinfo/<int:pk>/', quotation.rfqinfo, name='insert_pur'),
    path('quotation/rfqinfo/<int:pk>/', quotation.rfqinfo2, name='insert_pur'),
    path('purchaseorder/searchjiekou', purchaseorder.searchjiekou, name='search_pur'),
    path('purchaseorder/searchjiekouzhuanhua', purchaseorder.searchjiekouzhuanhua, name='search_pur'),
    path('purchaserequisition/pomanage', purchaserequisition.pomanage, name='search_pur'),
    path('purchaserequisition/prmanage', purchaserequisition.prmanage, name='search_pur'),
    path('purchaserequisition/quoma', purchaserequisition.quoma, name='search_pur'),
]

MM/views/auxiliary.py
import datetime
import pytz

def getRegex(string):
    if string == '' or string is None:
        return r'.*'
    else:
        return string

def getPk(string, type='*'):
    if string == '' or string is None:
        return r'.*'
    else:
        return str(int(string))

def getPkExact(string, type='*'):
    if string == '' or string is None:
        return ''
    else:
        return str(int(string))

def getDate(string):
    dateInfo = string.split('. ')
    string = datetime.date(
        year=int(dateInfo[2]), month=int(dateInfo[1]), day=int(dateInfo[0])
    )
    return string


def getDate2(string):
    dateInfo = string.split('. ')
    string = datetime.date(
        year=int(dateInfo[2]), month=int(dateInfo[1]), day=int(dateInfo[0])
    )
    return string

MM/views/document.py
import json
from django.shortcuts import get_object_or_404, render
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib import auth, messages
from django import forms
from django.db.models import QuerySet, Sum, F
from django.contrib.auth.decorators import login_required
from django.forms.models import model_to_dict
from django.utils import timezone
from datetime import datetime, timedelta
import datetime
from django.http import JsonResponse

from ..models import *
from .auxiliary import *


@login_required
def search_document_flow(request: HttpRequest):
    if request.method == 'POST':
        materialitem_id = request.POST.get('materialitemid')
        time_range = request.POST.get('time_range')

        orderitems = OrderItem.objects.all()

        if materialitem_id:
            orderitems = orderitems.filter(meterialItem__id__exact=materialitem_id)

        if time_range == '1':  # 近半年
            start_date = datetime.datetime.now() - datetime.timedelta(days=182)
        elif time_range == '2':  # 近三月
            start_date = datetime.datetime.now() - datetime.timedelta(days=91)
        else:
            start_date = None

        if start_date:
            orderitems = orderitems.filter(po__time__gte=start_date)

        data = {
            'orderitems': list(orderitems.values('po', 'po__euser__id', 'po__vendor__vname', 'id', 'itemId',
                                                 'meterialItem__material__mname', 'po__time')),
        }

        return JsonResponse(data)

    return render(
        request=request,
        template_name='../templates/document/search.html'
    )

@login_required
def display_document_flow(request: HttpRequest, pk):
    if request.method != 'POST':
        orderitem = get_object_or_404(OrderItem, pk=pk)
        po=orderitem.po
        materialitem = orderitem.meterialItem
        material=materialitem.material
        stock=materialitem.stock
        invoice=Invoice.objects.filter(orderItem=orderitem).first()
        goodreceipt=GoodReceipt.objects.filter(orderItem=orderitem).first()
        invoice_dict={}
        goodreceipt_dict={}
        if(invoice):
            invoice_dict = model_to_dict(invoice)
        if(goodreceipt):
            goodreceipt_dict = model_to_dict(goodreceipt)
        po_dict = model_to_dict(po)
        po_dict['time'] = po.time.strftime('%Y-%m-%d %H:%M:%S')  # Format datetime to string
        data = {
            'material': model_to_dict(material),
            'stock': model_to_dict(stock),
            'materialitem': model_to_dict(materialitem),
            'po': po_dict,
            'orderitem': model_to_dict(orderitem),
            'goodreceipt': goodreceipt_dict,
            'invoice': invoice_dict
        }

        return render(
            request=request,
            template_name='../templates/document/display.html',
            context=data
        )

MM/views/material.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib import auth, messages
from django import forms
from django.contrib.auth.decorators import login_required

from ..models import EUser, Material, MaterialItem, Stock
from .auxiliary import *

@login_required
def search_material(request: HttpRequest):
    if request.method == 'GET':
        return render(
            request=request,
            template_name='../templates/material/search.html'
        )
    else:
        return HttpResponse(status=405)

@login_required
def search_item_stock(request: HttpRequest):
    if request.method == 'GET':
        return render(
            request=request,
            template_name='../templates/material/stock.html'
        )
    else:
        return HttpResponse(status=405)

@login_required
def create_item(request: HttpRequest):
    if request.method == 'GET':
        return render(
            request=request,
            template_name='../templates/material/create.html'
        )
    else:
        return HttpResponse(status=405)

MM/views/user.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
import re
from django.shortcuts import redirect

from ..models import EUser

def login(request: HttpRequest) -> HttpResponse:
    if request.method == 'GET':
        return render(
            request=request,
            template_name='../templates/user/login.html',
        )
    elif request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        message = None
        if (password=='' or email==''):
            message = "部分字段为空"
        else:
            queryset = EUser.objects.filter(email__exact=email)
            if len(queryset) == 0:
                message = "用户名错误"
            else:
                euser = auth.authenticate(username=queryset.get().username, password=password)
                if euser is None:
                    message = "密码错误"
        if message is None:
            auth.login(request=request, user=euser)
            return HttpResponseRedirect(reverse('MM:home'))
        else:
            return render(
                request=request,
                template_name='../templates/user/login.html',
                context={'message': message}
            )


def register(request: HttpRequest) -> HttpResponse:
    if request.method == 'GET':
        return render(
            request=request,
            template_name='../templates/user/register.html',
        )
    elif request.method == 'POST':
        post = request.POST
        username = post.get('username')
        first_name = post.get('first_name')
        last_name = post.get('last_name')
        password = post.get('password')
        password1 = post.get('password2')
        email = post.get('email')
        sector = post.get('sector')
        phone = post.get('phone')
        question1 = post.get('question1')
        answer1 = post.get('answer1')
        question2 = post.get('question2')
        answer2 = post.get('answer2')

        message = None

        # 检查是否有空字段
        if (username == '' or password == '' or password1 == '' or email == '' or sector == '' or phone == '' or
                question1 == '' or question2 == '' or answer1 == '' or answer2 == ''):
            message = "部分字段为空"

        # 检查密码是否包含字母和数字
        elif not (re.search(r'[A-Za-z]', password) and re.search(r'[0-9]', password)):
            message = "密码必须同时包含字母和数字"

        # 检查电话是否为11位数字
        elif not re.match(r'^\d{11}$', phone):
            message = "电话必须为11位数字"

        # 检查邮箱格式是否正确
        elif not re.match(r'^[\w\.-]+@[\w\.-]+\.\w+$', email):
            message = "邮箱格式不正确"

        # 检查两次密码是否一致
        elif password != password1:
            message = "两次输入的密码不一致"

        # 检查邮箱是否已经注册
        else:
            queryset = EUser.objects.filter(email__exact=email)
            if len(queryset) > 0:
                message = "您的邮箱已被注册过"
            queryset = EUser.objects.filter(username__exact=username)
            if len(queryset) > 0:
                message = "您的用户名已被注册过"

        if message is None:
            euser = EUser(
                username=username,
                first_name=first_name,
                last_name=last_name,
                sector=sector,
                phone=phone,
                email=email,
                question1=question1, question2=question2,
                answer1=answer1, answer2=answer2,
            )
            euser.set_password(password)
            euser.save()
            messages.success(request=request, message="用户创建成功！")
            return HttpResponseRedirect(reverse('MM:login'))
        else:
            messages.error(request, message)
            return redirect('MM:register')


@login_required
def home(request):
    return render(
        request=request,
        template_name='../templates/user/index.html',
    )
    # return HttpResponse(request.user.username)

def logout(request):
    auth.logout(request=request)
    return HttpResponseRedirect(reverse('MM:login'))

MM/templates/template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MM</title>
    {% load static %}
    <!-- CSS -->
    <link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-chalk/index.css">
    <link href="{% static 'assets/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'assets/font-awesome/css/font-awesome.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/zabuto_calendar.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/js/gritter/css/jquery.gritter.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'assets/lineicons/style.css' %}">
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/style-responsive.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/notice.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/default.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/the-datepicker.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/purchase.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/fonts/icon1/iconfont.css' %}">
    <link href="{% static 'assets/css/base/jquery-ui-1.10.4.custom.css' %}" rel="stylesheet">

    <!-- 自定义CSS -->
    <style>
        /* 修改背景颜色 */
        body {
            background-color: #f5f5f5; /* 更柔和的灰色背景 */
        }

        /* 顶部导航栏 */
        .header {
            background-color: #2a3f54; /* 深蓝色背景 */
            border-bottom: 4px solid #e74c3c; /* 红色底部边框 */
        }

        /* LOGO样式 */
        .logo {
            color: #ecf0f1; /* 更显眼的白色字体 */
            font-weight: bold;
            font-size: 20px;
        }

        /* 顶部图标和按钮样式 */
        .sidebar-toggle-box .fa-bars,
        .nav .fa-user,
        .nav .fa-sign-out,
        .nav .dropdown-toggle span { /* 顶部图标和按钮文字 */
            color: #ffffff; /* 白色图标和文字 */
        }

        /* 侧边栏菜单 */
        #sidebar {
            background-color: #34495e; /* 深灰色背景 */
        }

        .nav.top-menu a span,
        .sidebar-menu > li > a span {
            color: #ffffff !important; /* 确保文字颜色变为白色 */
        }

        /* 导航菜单图标和文本 */
        .sidebar-menu > li > a {
            color: #ecf0f1; /* 更显眼的白色文本 */
            background-color: transparent; /* 透明背景 */
            border-left: 4px solid transparent;
            transition: all 0.3s ease;
        }

        /* 悬停效果 */
        .sidebar-menu > li > a:hover {
            background-color: #16a085; /* 青绿色悬停背景 */
            color: #ffffff; /* 白色文本 */
            border-left: 4px solid #e74c3c; /* 红色边框 */
        }

        /* 上层菜单项在选中和悬停状态下的背景颜色 */
        .sidebar-menu > li.active > a {
            background-color: #16a085; /* 统一的背景颜色 */
            color: #ffffff;
        }

        /* 子菜单项的背景颜色 */
        .sub-menu li a {
            background-color: #34495e; /* 深灰色背景，与侧边栏一致 */
            color: #ffffff !important; /* 白色字体 */
            border-left: 4px solid transparent;
            transition: all 0.3s ease;
        }

        /* 用户信息样式 */
        #user-id, #username {
            color: #ffffff; /* 白色字体 */
            font-weight: bold;
        }

        /* 调整图片样式 */
        .centered img {
            border-radius: 50%; /* 圆形图片 */
            border: 2px solid #ecf0f1; /* 白色边框 */
        }

        /* 侧边栏的阴影效果 */
        #sidebar {
            box-shadow: 0 2px 15px rgba(0, 0, 0, 0.2); /* 添加阴影效果 */
        }

        /* 侧边栏的滚动条样式 */
        #sidebar::-webkit-scrollbar {
            width: 8px;
        }
        #sidebar::-webkit-scrollbar-thumb {
            background-color: #16a085; /* 滚动条颜色 */
            border-radius: 10px;
        }

        /* 侧边栏标题样式 */
        .sidebar-menu .centered {
            color: #ffffff;
            font-weight: bold;
            font-size: 16px;
            padding: 10px 0;
        }

        /* 弹窗modal样式 */
        .modal-header{
            background-color:#2980b9;/* 深蓝色边框 */
        }
    </style>

    <!-- JS -->
    <!-- 基础库 -->

    <script src="{% static 'assets/js/jquery-1.12.0.min.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="https://unpkg.com/vue/dist/vue.global.js"></script>

    <script src="https://unpkg.com/element-ui/lib/index.js"></script>

    <!-- jQuery 插件 -->

    <script src="{% static 'assets/js/jquery-ui-1.10.4.custom.js' %}"></script>
    <script src="{% static 'assets/js/jquery.sparkline.js' %}"></script>
    <script src="{% static 'assets/js/jquery.scrollTo.min.js' %}"></script>
    <script src="{% static 'assets/js/gritter/js/jquery.gritter.js' %}"></script>
    <script src="{% static 'assets/js/gritter-conf.js' %}"></script>
    <script src="{% static 'assets/js/zabuto_calendar.js' %}"></script>
    <script src="{% static 'assets/js/the-datepicker.js' %}"></script>
    <script class="include" type="text/javascript" src="{% static 'assets/js/jquery.dcjqaccordion.2.7.js' %}"></script>
    <!-- 通知插件 -->
    <script src="{% static 'assets/js/notice.min.js' %}"></script>

    <!-- 图表与可视化库 -->
    <script src="{% static 'assets/js/chart-master/Chart.js' %}"></script>
    <script src="{% static 'assets/js/echarts.js' %}"></script>
    <script src="{% static 'assets/js/sparkline-chart.js' %}"></script>

    <!-- 代码高亮 -->
    <script src="{% static 'assets/js/highlight.min.js' %}"></script>

    {% block extra_css %}
    {% endblock %}
</head>

<body>

<section id="container">

    <header class="header black-bg">
        <div class="row">
            <div class="col-sm-8">
                <div class="sidebar-toggle-box">
                    <div class="fa fa-bars tooltips" data-placement="right" data-original-title=""></div>
                </div>
                <!--logo start-->
                <a href={% url 'MM:home' %} class="logo"><b>济同集团物料管理系统</b></a>
                <!--logo end-->
            </div>
            <div class="col-sm-4">
                <!-- 当前登录用户和退出按钮 -->
                <div class="row" style="margin: 16px 16px 16px 100px;">
                    <ul class="nav top-menu" style="align-content: center">
                        <li class="dropdown">
                            <a class="dropdown-toggle" href="">
                                <i class="fa fa-user"></i>
                                <span id="user-id"></span> <!-- 显示用户ID -->
                                <span id="username"></span> <!-- 显示用户名 -->
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'MM:logout' %}"> <!-- 退出按钮，指向登出URL -->
                                <i class="fa fa-sign-out"></i>
                                <span>退出</span>
                            </a>
                        </li>
                    </ul>
                </div>
                <!--  notification start -->
            </div>
        </div>
    </header>

    <aside>
        <div id="sidebar" class="nav-collapse ">
            <!-- sidebar menu start-->
            <ul class="sidebar-menu" id="nav-accordion">

                <li class="mt">
                    <a href="/mm/home/">
                        <i class="fa fa-dashboard"></i>
                        <span>主页</span>
                    </a>
                </li>

                <li class="sub-menu">
                    <a href="javascript:">
                        <i class="fa fa-desktop"></i>
                        <span>供应商管理</span>
                    </a>
                    <ul class="sub">
                        <a href="/mm/vendor/create/">创建新供应商</a>
                        <a href="/mm/vendor/search/">查看或修改供应商信息</a>
                        <a href="/mm/vendor/history/">供应商交易历史汇总</a>
                    </ul>
                </li>

                <li class="sub-menu">
                    <a href="javascript:">
                        <i class="fa fa-cogs"></i>
                        <span>商品管理</span>
                    </a>
                    <ul class="sub">
                        <a href="/mm/material/item/create/">创建新商品</a>
                        <a href="/mm/material/search/">查看或修改商品信息</a>
                        <a href="/mm/material/item/stock/">查看商品库存</a>
                    </ul>
                </li>

                <li class="sub-menu">
                    <a href="javascript:">
                        <i class="fa fa-th"></i>
                        <span>采购订单管理</span>
                    </a>
                    <ul class="sub">
                        <a href="/mm/purchaserequisition/prmanage">采购申请</a>
                        <a href="/mm/purchaserequisition/quoma">供应商评估管理</a>
                        <a href="/mm/purchaserequisition/pomanage">采购订单</a>
                    </ul>
                </li>

                <li class="sub-menu">
                    <a href="javascript:">
                        <i class="fa fa-tasks"></i>
                        <span>收货管理</span>
                    </a>
                    <ul class="sub">
                        <a href="/mm/receipt/orders/search/">创建商品收据</a>
                        <a href="/mm/receipt/search/">查看商品收据</a>
                        <a href="/mm/invoice/orders/search/">创建发票收据</a>
                        <a href="/mm/invoice/search/">查看发票收据</a>
                        <a href="/mm/invoice/payment/">付款</a>
                    </ul>
                </li>

                <li class="sub-menu">
                    <a href="javascript:">
                        <i class="fa fa-file"></i>
                        <span>文档流</span>
                    </a>
                    <ul class="sub">
                        <a href="/mm/document/search">查看文档流</a>
                    </ul>
                </li>

            </ul>
        </div>
    </aside>
</section>

{% block main_content %}
{% endblock %}

<script>
    const showMessage = (options) => {
        notice=new Notice();
        notice.showToast(options);
    }
</script>

<!-- 项目自定义脚本 -->
<script src="{% static 'assets/js/main.js' %}"></script>
<script src="{% static 'assets/js/common-scripts.js' %}"></script>
<script src="{% static 'assets/js/jquery.print.js' %}"></script>

<!-- Custom scripts -->
<script>
    hljs.highlightAll();
</script>
<script>
    $(document).ready(function(){
        $.ajax({
            url: "{% url 'MM:get_user_info' %}",  // 请求的URL
            method: "GET",
            success: function(response) {
                if (response.status === 'success') {
                    const user = response.data;
                    $('#user-id').text(`ID: ${user.uid}`);  // 显示用户ID
                    $('#username').text(`Name: ${user.username}`);  // 显示用户名
                } else {
                    console.log('Error:', response.message);
                }
            },
            error: function(xhr, status, error) {
                console.log('AJAX Error:', error);
            }
        });
    });
</script>

{% block js %}
{% endblock %}

</body>
</html>